[build]
  base = "client"             # Base directory where the command is executed
  publish = ".next"           # Publish directory relative to the base
  command = "npm run build"   # Command to build the project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
